[package]
name = "jakeb/arrow-simulator"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
React = "jsdotlua/react@17.0.2"
ReactRoblox = "jsdotlua/react-roblox@17.0.2"
ProfileService = "jakebball/profileservice@1.5.0"
Promise = "evaera/promise@4.0.0"
ReactSpring = "chriscerie/react-spring@2.0.0"
GoodSignal = "stravant/goodsignal@0.2.1"
RoactTemplate = "corecii/roact-template@0.2.0"
Observers = "sleitnick/observers@0.3.3"
RoactCompat = "jsdotlua/roact-compat@17.1.0"
Trove = "sleitnick/trove@1.1.0"